mv  learnqqword                             teachqqword
mv  learnqqmemory                           teachqqmemory
mv  learnffhistory                          teachffhistory
mv  learnffaoshu                            teachffaoshu
mv  learnqq51talk                           teachqq51talk
mv  learnffenglish                          teachffenglish
mv  learnqqchinese                          teachqqchinese
mv  learnword                               teachword
mv  learnqqmath                             teachqqmath
mv  learnffchinese                          teachffchinese
mv  learnqqkexue                            teachqqkexue
mv  learnqqwyw                              teachqqwyw
mv  learnprogramme                          teachprogramme
mv  learnffxiwangstar                       teachffxiwangstar
mv  learnffwyw                              teachffwyw
mv  learnffmath                             teachffmath
mv  learnqqaoshu                            teachqqaoshu
mv  learnffmemory                           teachffmemory
mv  learnqqhistory                          teachqqhistory
mv  learngimp                               teachgimp
mv  learnqqenglish                          teachqqenglish
mv  learnff51talk                           teachff51talk
mv  learnffkexue                            teachffkexue

